// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"--------------------------","status":false,"description":"---------------------------------------------------------------------","parameters":{}},
{"name":"VisuMZ_0_CoreEngine","status":true,"description":"[RPG Maker MZ] [Tier 0] Core Engine - bug fixes & enhancements","parameters":{"EscapeAlways:eval":"true","LevelUpFullHp:eval":"true","LevelUpFullMp:eval":"true"}},
{"name":"--------------------------","status":false,"description":"---------------------------------------------------------------------","parameters":{}},
{"name":"AltMenuScreen","status":true,"description":"","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"","parameters":{}},
{"name":"TextPicture","status":true,"description":"","parameters":{}},
{"name":"AutoSave","status":true,"description":"","parameters":{}},
{"name":"EnemyHPBars","status":true,"description":"Show HP bars above enemies in battle","parameters":{}}
];
